name: Generate Snake Animation

on:
  # Triggers the workflow every 24 hours
  schedule:
    - cron: "0 0 * * *"
  # Allows you to manually run the workflow
  workflow_dispatch:
  # Runs when someone pushes to the repository
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: <iamaparnaojha>
          outputs: dist/snake.svg

      # Step 3: Push the generated file back to the repository
      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m "Generate Snake Animation"
          git push
